### ISSUE TITLE
User Registration and Authentication

### ISSUE THREAD

**Issue by kimatron** [Vasileios20/JobAppTracker#5]
As a **new user**, I want to create an account so that I can **access the job application tracker**.

As a **registered user**, I want to log in to my account to **view my job applications**.

- Users can register with email and password
- Users can log in with their credentials
- Users can log out of their account
- Passwords are securely hashed and stored

1. **Set up User Model**

 Define User model with fields: username, email, password
 Implement password hashing
 Create database migration for User model

2. Implement User Registration

 Create registration form
 Implement form validation
 Create view/controller for handling registration
 Set up URL route for registration page

3. Implement User Login

 Create login form
 Implement authentication logic
 Create view/controller for handling login
 Set up URL route for login page

4. Implement User Logout

 Create logout functionality
 Set up URL route for logout
 Implement redirect after logout

5. Secure User Authentication

 Implement password strength requirements
 Set up password reset functionality
 Implement account lockout after multiple failed attempts

**Comment by Vasileios20** [comment]
functionality to signup/login/logout done.
Some basic css has been added, tried this one https://uiverse.io/yashasvi9199/silent-liger-75
![Image](https://github.com/user-attachments/assets/ad8e7e66-da76-4b0b-b712-1d1b0451387c)
![Image](https://github.com/user-attachments/assets/ed67ae16-e86b-46b2-abb5-67ab83a2122c)

![Image](https://github.com/user-attachments/assets/e3b5c85a-bff4-4823-8361-685e41599f29)
